### ISSUE TITLE
Persist the form in db

### ISSUE THREAD

**Issue by RemiDesgrange** [kvesteri/wtforms-alchemy#126]
Hi, 

I found nothing in the doc.

My question is simple : how to save data from my form onces submited, the doc tells nothing about it. I assumed that since ModelForm was like Django one, I should just do `myForm.save()`.

if I take the quickstart, what would be the code with saving ?

my setup:
sqlalchemy : 1.1.15
wtforms:  2.1
wtforms_alchemy : 0.16.5

```python
import sqlalchemy as sa
from sqlalchemy import create_engine
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from wtforms_alchemy import ModelForm
from flask import Flask, request

engine = create_engine('sqlite:///:memory:')
Base = declarative_base(engine)
Session = sessionmaker(bind=engine)
session = Session()

class User(Base):
    __tablename__ = 'user'

    id = sa.Column(sa.BigInteger, autoincrement=True, primary_key=True)
    name = sa.Column(sa.Unicode(100), nullable=False)
    email = sa.Column(sa.Unicode(255), nullable=False)


class UserForm(ModelForm):
    class Meta:
        model = User

app = Flask()

@app.route('/')
def test():
    form = UserForm(request.form)
    if form.validate_on_submit():
       form.save() # ?? or populate_obj but what's the point of creating a new instance of a entities ?
       return redirect(url_for('/success'))
   return render_template('my_template.html', form=form)
```

am I missing something ?

**Comment by chriscauley** [comment]
If anyone else stumbles on this in the future, you `populate_obj` and save in the usual manner.

``` python
@app.route('/person/edit/<id>/', methods=['GET', 'POST'])
def edit_person(id):
    person = Person.query.get_or_404(id)
    form = PersonForm(obj=person)
    if form.validate_on_submit():
        form.populate_obj(person)
        db.session.add(person)
        db.session.commit()
```

Also note that you do `MyForm(data,obj=obj)` instead of django's `MyForm(data,instance=obj)`

Source: https://stackoverflow.com/a/3859771

**Comment by PetrDlouhy** [comment]
Hi,

I think, that this issue was about the documentation, so I think, this should be reopened. The documentation now is really BAD.

I would consider saving the object to DB basic functionality, but the docs doesn't contain a word about this.

I am coming from the world of Django and I am really struggling even with the basic CRUD in Flask.
