### ISSUE TITLE
[question] Proper way to deal with i18n currency

### ISSUE THREAD

**Issue by arthurbarros** [kvesteri/wtforms-alchemy#89]
@kvesteri Could you enlighten me of how to solve this problem? 

```python
class Product(Base):
    __tablename__ = 'product'

    name = db.Column(db.String(80), nullable=False)
    price = db.Column(db.Numeric(4), nullable=True)
```

and I got this as a wtform

```python
class ProductRegisterForm(ModelForm):
    class Meta:
        model = Product
        only = ['name', 'price']
``` 

The problem is, here in Brazil our ponctuation for currency is like this: R$ 1.000,00 and this is the same as $ 1,000.00. We use dot as the thousand poncuation and commas as decimal poncuation.

The ```form.errors``` return the following for me

```python
[('price', [u'Not a valid decimal value'])]

```

I'm really lost here.
Thanks

**Comment by kvesteri** [comment]
I guess the easiest way would be just to define a custom field for it.

```python
class ProductRegisterForm(ModelForm):
    class Meta:
        model = Product
        only = ['name']

    price = MyBrazilianCurrencyField(...)
```

**Comment by arthurbarros** [comment]
Worked like a charm! Thanks @kvesteri
