### ISSUE TITLE
Badges are not working.

### ISSUE THREAD

**Issue by alephmelo** [kvesteri/wtforms-alchemy#93]
This link https://crate.io/packages/WTForms-Alchemy/ is broken.
![screen shot 2016-01-26 at 10 12 46 am](https://cloud.githubusercontent.com/assets/6146240/12581462/6ed14d0c-c415-11e5-8c69-1c80f2a05b7b.png)

**Comment by kvesteri** [comment]
Fixed, thanks for reporting.

**Comment by alephmelo** [comment]
You're welcome! :+1:
