### ISSUE TITLE
wtforms-components 0.10 broke wtforms-alchemy

### ISSUE THREAD

**Issue by hyperknot** [kvesteri/wtforms-alchemy#95]
This removal in components: https://github.com/kvesteri/wtforms-components/issues/39

causes a serious bug, as `wtforms-alchemy` depends on `wtforms-components`'s PhoneNumberField.

Now every `wtforms_alchemy` install is broken, unless manually pinning down the components dependency (which almost no one does).

Please publish a fix release of either library to pypi.

**Comment by kvesteri** [comment]
Now fixed (as of 0.15.0).
